### ISSUE TITLE
container not respecting docker-compose link option

### ISSUE THREAD

**Issue by citizenrich** [jembi/openhim-docker#1]
I'm setting up a docker-compose file to fire up openhim-core and mongo. There's an error in which it seems the openhim-core container is not connecting correctly to a mongo container.

Docker logs for the openhim container: 'MongoError: failed to connect to server [localhost:27017] on first connect'. This suggests that the env var for mongodb is not being passed along. But, 'mongo' is added to /etc/hosts in a docker-compose with the link option, so it's definitely reachable from the node container. Thoughts?

Platform: Ubuntu 14.04
Docker version 17.03.1-ce

docker-compose.yml:

version: '3'

services:

  openhim-docker:
    container_name: openhim-core
    image: jembi/openhim-core
    ports:
      - "8080:8080"
    links:
      - mongo
    environment:
      - mongo_url=mongodb://mongo/openhim

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

**Comment by rcrichton** [comment]
Hi @citizenrich, when I run the image with `docker run` the environment variable works. It must be some issue with the linking config. I haven't been able to figure it yet unfortunately. Perhaps you want to make sure mongo is reachable from the openhim container? I'm also wondering if you need to expose the 27017 port as I think this exposed it to the host and might affect the link network.

**Comment by citizenrich** [comment]
Hi @rcrichton, cheers. I've had another look. Must be something weird I'm doing in the docker-compose. Can you share a working example that uses a mongo container? The link definitely works.

docker run -it --link mongo:mongo --net openhimdocker_default -it jembi/openhim-core /bin/bash

root@99f098f7d724:/usr/src/app# ping mongo
PING mongo (172.18.0.2): 56 data bytes
64 bytes from 172.18.0.2: icmp_seq=0 ttl=64 time=0.097 ms
...
root@99f098f7d724:/usr/src/app# curl mongo:27017
It looks like you are trying to access MongoDB over HTTP on the native driver port.
...
root@99f098f7d724:/usr/src/app# mongo_url=mongodb://mongo/openhim node lib/server.js
...
MongoError: failed to connect to server [localhost:27017] on first connect
...
root@99f098f7d724:/usr/src/app# mongo_url=mongodb://mongo:27017/openhim node lib/server.js
...
MongoError: failed to connect to server [localhost:27017] on first connect
...

**Comment by rcrichton** [comment]
This is what I tried and the connection error message changes depending on the env that I supply. I haven't dug in much more than that though: `docker run --env mongo_url=mongodb://test/test jembi/openhim-core`

**Comment by napiergit** [comment]
Hi Richard.  Here is a working docker-compose file.  Note the additional
environment variable.

version: '3'

services:
  openhim-docker:
    container_name: openhim-core
    image: jembi/openhim-core
    depends_on:
     - mongo
    ports:
      - "8080:8080"
    environment:
      mongo_url: mongodb://mongo/openhim
      mongo_atnaUrl: "mongodb://mongo/openhim"

  mongo:
    image: mongo:3
    ports:
      - "27017:27017"

**Comment by citizenrich** [comment]
@napiergit @rcrichton Genius. It works now. Cheers!
