### ISSUE TITLE
docker-compose for the full stack

### ISSUE THREAD

**Issue by citizenrich** [jembi/openhim-docker#2]
I think making the full openhim stack easier to launch is ideal here, and I sat down to do that today.

https://github.com/citizenrich/openhim-stack-docker

Then I saw in linking back to your Dockerfiles that you posted one for console! Awesome. Ideally, I'd really like to see this (your) repo contain the full working docker-compose so that users can get the stack up quickly for mediator development on Windows, Mac, and Linux using Docker. Happy to help.

**Comment by rcrichton** [comment]
Hi @citizenrich thanks very much. We are planning on doing some more docker work and a docker-compose file is definitely on the cards. We'll take a look at what you have done and see if we can get it up into our repo and working with our images.

**Comment by BMartinos** [comment]
https://github.com/jembi/openhim-core-js/blob/master/infrastructure/docker-compose.yml

Getting the OpenHIM up and running quickly to start development, you can run the below command
`docker-compose up -d`
